import '../globals.css'
import styles from './server.module.css';



export const metadata = {
  title: 'server',
  description: 'Generated by create next app',
  code: 'viewport content="width=device-width, initial-scale=1.0"'
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={styles.fonServer}>
        {children}
        </body>
    </html>
  )
}
